apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chartRef:
      kind: OCIRepository
      name: postgresql
      namespace: default
      interval: 10m
  values:
    