apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql-dev
  namespace: default
spec:
  interval: 1m
  chartRef:
    kind: OCIRepository
    name: postgresql
    namespace: default
  values:
    