apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: postgresql
        namespace: flux-system
      interval: 10m
  values:
    