apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: postgresql
      version: '4.0.x'
      sourceRef:
        kind: OCIRepository
        name: postgresql
      interval: 10m
  values:
    