apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: erigon-holesky
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: ethereum-helm-charts/erigon
      version: '1.0.12'
      sourceRef:
        kind: HelmRepository
        name: erigon
        namespace: flux-system
      interval: 10m
  values:
    image:
      tag: "2.61.3"
    extraArgs:
      - --chain=holesky