apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: harbor
      version: '1.16.x'
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
      interval: 10m
  values:
    