apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: default
spec:
  interval: 1m
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: postgresql
    namespace: flux-system
  values:    
    containerPorts:
      postgresql: 9876
    global:
      postgresql:
        auth:
          username: "dev"
          password: "dev"
          database: "dev"
        service:
          ports:
            postgresql: 9876
    